# Generated by Django 5.2.12 on 2026-03-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('tipo', models.CharField(choices=[('avulso', 'Avulso'), ('mensalista', 'Mensalista')], default='avulso', max_length=10, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor por Hora')),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Diário')),
                ('tipo_veiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('todos', 'Todos')], default='todos', max_length=5, verbose_name='Tipo de Veículo')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifa',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(auto_now_add=True, verbose_name='Entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aberto', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('tipo', models.CharField(choices=[('admin', 'Admin'), ('operador', 'Operador')], default='operador', max_length=8, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('deficiente', 'Deficiente'), ('idoso', 'Idoso')], default='carro', max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada')], default='livre', max_length=8, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'db_table': 'vaga',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_debito', 'Cartão Débito'), ('cartao_credito', 'Cartão Crédito'), ('pix', 'PIX')], max_length=20, verbose_name='Forma de Pagamento')),
                ('pago_em', models.DateTimeField(auto_now_add=True, verbose_name='Pago em')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarifa', verbose_name='Tarifa')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamento',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaria',
                'verbose_name_plural': 'Avarias',
                'db_table': 'avaria',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vaga', verbose_name='Vaga'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo')),
                ('cor', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cor')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculo',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo', verbose_name='Veículo'),
        ),
    ]
