# Generated by Django 5.2.12 on 2026-04-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tarifa_horarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifa',
            options={'ordering': ['hora_inicio', 'tipo_veiculo', 'descricao'], 'verbose_name': 'Tarifa', 'verbose_name_plural': 'Tarifas'},
        ),
    ]
