# Generated by Django 5.2.12 on 2026-04-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tarifa_options'),
        ('app', '0004_user_native_and_avaria_vehicle'),
    ]

    operations = [
    ]
