# Generated by Django 5.2.12 on 2026-04-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20260420_1916'),
        ('app', '0005_vaga_numero_integer'),
    ]

    operations = [
    ]
