# Generated by Django 5.2.12 on 2026-04-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20260420_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaga',
            options={'ordering': ['numero'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
    ]
