# Generated by Copilot on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_vaga_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="cliente",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, to="app.cliente", verbose_name="Cliente"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="veiculo",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to="app.veiculo", verbose_name="Veículo"),
        ),
    ]
