# Generated by Django 5.2.12 on 2026-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ticket_veiculo_cliente_opcionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='periodo',
            field=models.CharField(choices=[('hora', 'Hora'), ('dia', 'Dia (valor fixo)'), ('semana', 'Semana (valor fixo)'), ('mes', 'Mês (valor fixo)')], default='hora', max_length=10, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='valor_fixo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Fixo'),
        ),
    ]
