# Generated by Copilot on 2026-05-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tarifa_periodo_tarifa_valor_fixo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='valor_diaria',
        ),
    ]
